ARG ERIC_ENM_MODELS_IMAGE_REPO=armdocker.rnd.ericsson.se/proj-enm
ARG ERIC_ENM_MODELS_IMAGE_NAME=eric-enm-models-base-image
ARG LATEST_ERIC_ENM_MODELS_IMAGE_TAG=latest

FROM ${ERIC_ENM_MODELS_IMAGE_REPO}/${ERIC_ENM_MODELS_IMAGE_NAME}:${LATEST_ERIC_ENM_MODELS_IMAGE_TAG}

ARG BUILD_DATE=unspecified
ARG IMAGE_BUILD_VERSION=unspecified
ARG GIT_COMMIT=unspecified
ARG ISO_VERSION=unspecified
ARG RSTATE=unspecified
ARG CXC=unspecified

LABEL \
com.ericsson.product-number=$CXC \
com.ericsson.product-revision=$RSTATE \
enm_iso_version=$ISO_VERSION \
org.label-schema.name="ENM Models Group" \
org.label-schema.build-date=$BUILD_DATE \
org.label-schema.vcs-ref=$GIT_COMMIT \
org.label-schema.vendor="Ericsson" \
org.label-schema.version=$IMAGE_BUILD_VERSION \
org.label-schema.schema-version="1.0.0-rc1"